- name: download golang tarball
  get_url:
    url: "https://go.dev/dl/go{{ version }}.{{ ansible_system|lower }}-{{ ansible_architecture }}.pkg"
    dest: "{{ local_home }}/Downloads/go{{ version }}.{{ ansible_system|lower }}-{{ ansible_architecture }}.pkg"

- name: install golang pkg file
  shell: "installer -pkg {{ local_home }}/Downloads/go{{ version }}.{{ ansible_system }}-{{ ansible_architecture }}.pkg -target /"
  become: yes
  args:
    executable: /bin/bash
    creates: "/usr/local/go"

- name: Remove golang pkg after install
  file:
    path: "{{ local_home }}/Downloads/go{{ version }}.{{ ansible_system }}-{{ ansible_architecture }}.pkg"
    state: "absent"
