- name: create golang directories
  file:
    dest: "/home/{{ user }}/src"
    state: directory

- name: download golang tarball
  get_url:
    url: "https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz" 
    dest: "/home/{{ user }}/src/go1.13.7.linux-amd64.tar.gz"
    sha256sum: "b3dd4bd781a0271b33168e627f7f43886b4c5d1c794a4015abf34e99c6526ca3" 

- name: extract
  unarchive:
    src: "/home/{{ user }}/src/go1.13.7.linux-amd64.tar.gz"
    dest: "/home/{{ user }}/" 
