---
- name: Sync bash-it repo
  git:
    repo: 'https://github.com/Bash-it/bash-it.git'
    dest: "{{ local_home }}/.bash_it"
    depth: 1
    version: '{{ version }}'
  become_user: '{{ user }}'

- name: Install GNU bash since MacOs uses old version
  homebrew: name=bash state=present
  when: ansible_distribution == "Darwin"


- name: Create shell directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0700
    owner: '{{ user }}'
  with_items:
    - "{{ local_home }}/.shell"
    - "{{ local_home }}/.ssh"
    - "{{ local_home }}/.ssh/config.d"
