##
# Ansible playbook to configure desktop 
#

---
- hosts: local

  roles:
    - common       # common packages
    - terraform    # Install's terraform 
      #- mas  # Mac Apps Store apps
    - { role: mas, when: ansible_os_family == 'Darwin' } # Mac Apps Store apps
   
