##
# Ansible playbook to configure desktop 
#

---
- hosts: local

  vars:
    - local_home: "{{ lookup('env', 'HOME') }}"
    - user: "{{ lookup('env', 'USER') }}"

  roles:
#    - { role: mas, when: ansible_os_family == 'Darwin' } # Mac Apps Store, mas, brew and cask apps
    - common     # common package and tools, silversearcher, curl, nmap, make, gcc, etc.
#    - conky      # Conky for ubuntu 
    - docker     # Docker repo and install packages or docker from brew cask for mac
    - dropbox    # Install dropbox from deb package or dropbox from brew cask for mac
    - keepass    # Install keepass ppa and package or keepassx for mac
    - slack      # Install slack 
#    - terraform  # Install terraform
#    - vim        # setup vim pathogen and sync vim plugins
   
