##
# Ansible playbook to configure mac or ubuntu workstation
##
---
- hosts: local

  vars:
    - local_home: "{{ lookup('env', 'HOME') }}"
    - user: "{{ lookup('env', 'USER') }}"

  roles:
    #- { role: mas, when: ansible_os_family == 'Darwin' } # Mac Apps Store, mas
    - common      # common package and tools, silversearcher, curl, nmap, make, gcc, etc.
    - { role: container, tags: 'container' }  # install a terminal (iterm2 for mac and qterminal for ubuntu)
    - { role: terminal, tags: 'terminal' }  # install a terminal (iterm2 for mac and qterminal for ubuntu)
    #- awscli      # pip3 install awscli (mac and ubuntu)
    #- megasync     # Install megasync from deb package or from brew cask for mac
    #- golang      # Install golang
    #- keepass     # Install keepass
    - sdkman      # Install sdkman
    #- slack       # Install slack
    - { role: shell, tags: 'shell', version: v3.0.3 } # Shell related tasks (clones bash-it)
    - { role: tfenv, tags: 'tfenv'  # Install tfenv to manage terraform version
    #- vagrant     # Install hashicorp vagrant
    - vim_plugins # setup vim pathogen and sync vim plugins
    #- virtualbox  # Install virtualbox
    #- vscode      # Install visualstudiocode
    # Ubuntu specific roles:
    - { role: conky, when: ansible_os_family == 'Ubuntu' } # Conky performace wigit for ubuntu desktop
    - { role: pinta, when: ansible_os_family == 'Ubuntu' } # Ubuntu only - install simple paint application
