##
# Ansible playbook to configure desktop 
#

---
- hosts: local

  vars:
    - local_home: "{{ lookup('env', 'HOME') }}"
    - user: "{{ lookup('env', 'USER') }}"

  roles:
#    - { role: mas, when: ansible_os_family == 'Darwin' } # Mac Apps Store, mas, brew and cask apps
    - common     # common package and tools, silversearcher, curl, nmap, make, gcc, etc.
#    - conky      # Conky for ubuntu
    - docker     # Docker repo and install packages or from brew cask for mac
    - dropbox    # Install dropbox from deb package or from brew cask for mac
    - keepass    # Install keepass
    - slack      # Install slack
    - shell      # Shell related tasks
    - tfenv      # Install tfenv to manage terraform 
#    - vim        # setup vim pathogen and sync vim plugins
    - virtualbox # Install virtualbox
