##
# Ansible playbook to configure desktop 
#

---
- hosts: local

  vars:
    - local_home: "{{ lookup('env', 'HOME') }}"
    - user: "{{ lookup('env', 'USER') }}"

  roles:
    #    - { role: mas, when: ansible_os_family == 'Darwin' } # Mac Apps Store, mas, brew and cask apps
#    - common     # common packages
#    - conky      # conky for ubuntu 
#    - docker     # add docker repo and install packages
    - dropbox    # Install dropbox from remote deb package
#    - keepass    # Install keepass ppa and package
#    - terraform  # Install's terraform 
#    - vim        # setup vim pathogen and sync vim plugins
   
