##
# Ansible playbook to configure mac or ubuntu workstation
##
---
- hosts: local

  vars:
    - local_home: "{{ lookup('env', 'HOME') }}"
    - user: "{{ lookup('env', 'USER') }}"

  roles:
    - {role: common, tags: 'common'}                    # common package and tools, silversearcher, curl, nmap, make, gcc, etc.
    - {role: container, tags: 'container'}              # install a terminal (iterm2 for mac and qterminal for ubuntu)
    - {role: python, tags: 'python'}                    # install miniconda and py3.8, py3.9, and py3.10 envrionments
    - {role: nodejs, tags: 'nodejs', version: v0.39.1}  # Install nvm (node version manager)
    - {role: sdkman, tags: 'sdkman'}                    # Install sdkman
    - {role: shell, tags: 'shell', version: v3.0.3}     # Shell related tasks (clones bash-it)
    - {role: terminal, tags: 'terminal'}                # install iterm2 for mac and qterminal for ubuntu
    - {role: tfenv, tags: 'tfenv'}                      # Install tfenv terraform version manger
    - {role: vim_plugins, tags: 'vim_plugins'}          # setup vim pathogen and sync vim plugins
    #- awscli      # pip3 install awscli (mac and ubuntu)
    #- megasync    # Install megasync from deb package or from brew cask for mac
    #- golang      # Install golang
    #- keepass     # Install keepass
    #- slack       # Install slack
    #- vagrant     # Install hashicorp vagrant
    #- virtualbox  # Install virtualbox
    #- vscode      # Install visualstudiocode
    # Ubuntu specific roles:
    - {role: conky, when: ansible_os_family == 'Debian'}  # Conky performace wigit for ubuntu desktop
    - {role: pinta, when: ansible_os_family == 'Debian'}  # Ubuntu only - install simple paint application
