##
# Ansible playbook to configure desktop 
#

---
- hosts: local

  roles:
    - common       # common packages
    - terraform    # Install's terraform 
    - { role: mas, when: ansible_os_family == 'Darwin' } # Mac Apps Store, mas, brew and cask apps
    - vim # setup vim pathogen and sync vim plugins
   
