##
# Ansible playbook to configure desktop 
#

---
- hosts: local

  roles:
    #    - { role: mas, when: ansible_os_family == 'Darwin' } # Mac Apps Store, mas, brew and cask apps
    - common     # common packages
    - terraform  # Install's terraform 
    - vim        # setup vim pathogen and sync vim plugins
   
