---

common_packages:
- bzip2
- curl
- elixir
- firefox
- git
- gcc
- jsonnet
- jq
- nmap
- ngrep
- openssl
- pssh
- shellcheck
- tree
- vim
- vlc
- watch
- wget

install_ubuntu_packages:
- alsa-base
- alsa-utils
- apt-transport-https
- aptitude
- ca-certificates
- chrony
- bash-completion
- bluez
- build-essential
- dkms
- git-core
- git-flow
- git-email
- git-extras
- golang-go
- gnupg-agent
- gstreamer1.0-alsa
- gstreamer1.0-plugins-base-apps
- gstreamer1.0-pulseaudio
- gzip
- htop
- linux-headers-generic
- openssh-server
- pwgen
- pulseaudio
- software-properties-common
- silversearcher-ag
- tmux
- terminator
- tcpdump
- tar
- unzip
- ubuntu-restricted-extras
- vim
- vim-gtk
- wireless-tools
- xorg

remove_ubuntu_packages:
- aisleriot
- ack
- gbrainy
- gnome-mines
- gnome-sudoku
- gnome-mahjongg
- gnome-games-common
- libgnome-games-support-common
- unity-webapps-common 
