---
# packages that can be installed with apt/ubuntu or brew/darwin
common_packages:
- bzip2
- curl
- elixir
- git
- gcc
- gzip
- htop
- jq
- nmap
- ngrep
- netcat
- openssl
- pssh
- shellcheck
- tree
- tcpdump
- watch
- wget
- yamllint

# packaged only found on ubuntu
install_ubuntu_packages:
- alsa-base
- alsa-utils
- apt-transport-https
- aptitude
- ca-certificates
- chrony
- clamav
- clamav-daemon
- bash-completion
- bluez
- build-essential
- dkms
- git-core
- git-flow
- git-email
- git-extras
- golang-go
- gnupg-agent
- gstreamer1.0-alsa
- gstreamer1.0-plugins-base-apps
- gstreamer1.0-pulseaudio
- linux-headers-generic
- mtr
- mc
- nnn
- openssh-server
- pwgen
- pulseaudio
- pydf
- redshift-gtk
- software-properties-common
- silversearcher-ag
- smbclient
- tmux
- tar
- unzip
- ubuntu-restricted-extras
- vim-gtk
- vlc
- wireless-tools
- xorg

brew_packages:
- autoconf
- automake
- awscli
- elixir
- fzf
- kcat
- kubernetes-cli
- macvim
- mas
- node
- packer
- the_silver_searcher

remove_ubuntu_packages:
- aisleriot
- ack
- five-or-more
- four-in-a-row
- gbrainy
- gnome-chess
- gnome-mines
- gnome-sudoku
- gnome-mahjongg
- gnome-games-common
- gnome-taquin
- gnome-tetravex
- hitori
- iagno
- lightsoff
- libgnome-games-support-common
- quadrapassel
- swell-foop
- tali
- unity-webapps-common 
