- name: Install Jetbrains dependancy package libfuse2
  apt: pkg=libfuse2 state=present
  become: yes

- name: Extract tar to {{ local_home }} on Linux systems
  unarchive:
    src: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{ version }}.tar.gz"
    dest: "{{ local_home }}"
    remote_src: yes
    creates: "{{ local_home }}/jetbrains-toolbox-{{ version }}"

- name: Execute Jetbrains install script 
  script: "{{ local_home }}/jetbrains-toolbox-{{ version }}/jetbrains-toolbox"

- name: Remove jetbrains dir after install
  file:
    path: "{{ local_home }}/jetbrains-toolbox-{{ version }}"
    state: absent
