- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Add HashiCorp signing key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp.asc
    mode: '0644'
  become: yes

- name: Add HashiCorp repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  become: yes

- name: Update cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install vagrant package 
  apt: pkg=vagrant state=present
  become: yes
