---
- name: Install Code from snap
  snap:
    name: code
    classic: yes
  become: yes
  when: ansible_distribution == "Ubuntu"

- name: Install VSCode from homebrew cask
  homebrew_cask: name=visual-studio-code state=present
  when: ansible_distribution == "Darwin"
