- name: vim | setup directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  with_items:
    - "{{ local_home }}/.vim"
    - "{{ local_home }}/.vim/bundle"
    - "{{ local_home }}/.vim/bin"
    - "{{ local_home }}/.vim/autoload"
    - "{{ local_home }}/.vim/undo"

- name: vim | sync pathogen repo
  get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ local_home }}/.vim/autoload/pathogen.vim"
    owner: '{{ user }}'

- name: vim | sync vim repos
  git:
    repo: '{{ item }}'
    dest: "{{ local_home }}/.vim/bundle/{{ item | basename | regex_replace('.git','') }}"
  become_user: '{{ user }}'
  with_items: "{{ vim_plugin_repos }}"

    # not ready to do this yet
    #- name: vim | setup vimrc
    #  template:
    #    src: templates/gvimrc
    #    dest: "{{ local_home }}/.gvimrc"
    #    owner: '{{ user }}'
    #    mode: 0755

    #- name: vim | setup vimrc
    #  template:
    #    src: templates/vimrc
    #    dest: "{{ local_home }}/.vimrc"
    #    owner: '{{ user }}'
    #    mode: 0755
