- name: vim | setup directories
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    owner: '{{ user }}'
  with_items:
    - "{{ local_home }}/.vim"
    - "{{ local_home }}/.vim/bundle"
    - "{{ local_home }}/.vim/bin"
    - "{{ local_home }}/.vim/autoload"
    - "{{ local_home }}/.vim/undo"

- name: vim | sync pathogen repo
  get_url:
    url: https://tpo.pe/pathogen.vim 
    dest: "{{ local_home }}/.vim/autoload/pathogen.vim"
    owner: '{{ user }}'

- name: vim | sync vim repos
  git:
    repo: '{{ item }}'
    dest: "{{ local_home }}/.vim/bundle/{{ item | basename | regex_replace('.git','') }}"
  become_user: '{{ user }}'
  with_items:
    vim_plugin_repos:
            #    - https://github.com/w0rp/ale.git
            #    - https://github.com/maximbaz/lightline-ale.git
            #    - https://github.com/itchyny/lightline.vim
            #    - https://github.com/itchyny/vim-gitbranch.git
            #    - https://github.com/sjl/vitality.vim.git
            #    - https://github.com/mhinz/vim-startify.git
            #    - https://github.com/scrooloose/nerdtree.git
            #    - https://github.com/rkulla/pydiction.git
            #    - https://github.com/tpope/vim-bundler.git
            #    - https://github.com/tpope/vim-fugitive.git
            #    - https://github.com/tpope/vim-endwise.git
            #    - https://github.com/tpope/vim-unimpaired.git
            #    - https://github.com/tpope/vim-surround.git
            #    - https://github.com/tpope/vim-repeat.git
            #    - https://github.com/tpope/vim-commentary.git
            #    - https://github.com/godlygeek/tabular.git
            #    - https://github.com/altercation/vim-colors-solarized.git
            #    - https://github.com/ervandew/supertab.git
            #    - https://github.com/mileszs/ack.vim.git
            #    - https://github.com/ntpeters/vim-better-whitespace.git

    # not ready to do this yet
    #- name: vim | setup vimrc
    #  template:
    #    src: templates/gvimrc
    #    dest: "{{ local_home }}/.gvimrc"
    #    owner: '{{ user }}'
    #    mode: 0755

    #- name: vim | setup vimrc
    #  template:
    #    src: templates/vimrc
    #    dest: "{{ local_home }}/.vimrc"
    #    owner: '{{ user }}'
    #    mode: 0755
