---
- name: download miniconda
  get_url:
    url: "{{ downloads[ansible_os_family][ansible_architecture]['script'] }}"
    checksum: "{{ downloads[ansible_os_family][ansible_architecture]['checksum'] }}"
    dest: "{{ local_home }}/conda_install.sh"
    owner: '{{ user }}'

- name: install miniconda
  shell: "{{ local_home }}/conda_install.sh -b -p {{ local_home }}/miniconda"
  args:
    executable: /bin/bash
    creates: "{{ local_home }}/miniconda/bin/conda"

- name: create miniconda python {{ item }} environment
  shell: "{{ local_home }}/miniconda/bin/conda create -n 'py{{ item }}' python={{ item }}"
  args:
    creates: "{{ local_home }}/miniconda/envs/py{{ item }}/bin/python"
  with_items:
    - 3.8
    - 3.9
    - 3.10
