- name: Install
  apt: name=conky-std state=present
  become: yes
  tags: conky 

- name: create config directory
  file:
    path: /home/{{ user }}/.config/autostart
    state: directory

- name: configure autostart 
  template: 
    src: conky.desktop.j2 
    dest: /home/{{ user }}/.config/autostart/conky.desktop
  tags: conky 

- name: .conkyrc
  template: 
    src: conkyrc.j2 
    dest: /home/{{ user }}/.conkyrc
  tags: conky 
