---
  #- name: Install Mac apps store apps
  #- roles:
  #- geerlingguy.mas
- name: install mac store apps
  include_role:
    name: geerlingguy.mac.mas
  vars:
    mas_installed_apps:
      - { id: 497799835, name: "Xcode" }
      - { id: 552792489, name: "StatusClock" } 
    mas_upgrade_all_apps: yes
