- name: Ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes

- name: Add Docker signing key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: yes

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Update cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install docker apt packages 
  apt: 
    pkg: ['docker-ce', 'docker-ce-cli', 'containerd.io'] 
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  become: yes
