- name: Add Docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker signing key
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Update cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install docker apt packages 
  apt: 
    pkg: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose'] 
    state: present
  become: yes

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
  become: yes
