- name: Create megasync directory
  file:
    path: '{{ local_home }}/MEGAsync'
    state: directory
    owner: '{{ user }}'

- name: Install megasync desktop
  apt:
     deb: https://mega.nz/linux/repo/xUbuntu_{{ ansible_distribution_version }}/amd64/megasync-xUbuntu_{{ ansible_distribution_version }}_amd64.deb 
  become: yes
