vim_plugin_repos:
- https://github.com/w0rp/ale.git
- https://github.com/maximbaz/lightline-ale.git
- https://github.com/itchyny/lightline.vim
- https://github.com/itchyny/vim-gitbranch.git
- https://github.com/sjl/vitality.vim.git
- https://github.com/mhinz/vim-startify.git
- https://github.com/scrooloose/nerdtree.git
- https://github.com/rkulla/pydiction.git
- https://github.com/tpope/vim-bundler.git
- https://github.com/tpope/vim-fugitive.git
- https://github.com/tpope/vim-endwise.git
- https://github.com/tpope/vim-unimpaired.git
- https://github.com/tpope/vim-surround.git
- https://github.com/tpope/vim-repeat.git
- https://github.com/tpope/vim-commentary.git
- https://github.com/godlygeek/tabular.git
- https://github.com/altercation/vim-colors-solarized.git
- https://github.com/ervandew/supertab.git
- https://github.com/mileszs/ack.vim.git
- https://github.com/ntpeters/vim-better-whitespace.git
