---
- name: Sync tfenv repo
  git:
    repo: 'https://github.com/tfutils/tfenv.git'
    dest: "{{ local_home }}/.tfenv"
    depth: 1
  become_user: '{{ user }}'

- name: Link .tfenv/bin to {{ local_home }}/bin
  file:
    src: "{{ local_home }}/.tfenv/bin/{{ item }}"
    dest: "{{ local_home }}/bin/{{ item }}"
    state: link
  loop:
    - tfenv
    - terraform
