---
- name: Install Slack from snap
  snap:
    name: slack 
    classic: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Install Slack from homebrew cask
  homebrew_cask: name=slack state=present
  when: ansible_os_family == "Darwin"
