- name: Install deb package 
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2019.02.14_amd64.deb 
  become: yes

- name: Install python3-gpg
  apt: pkg=python3-gpg state=present
  become: yes
