---
- name: Download DisplayLink APT repository keyring
  get_url:
    url: "https://www.synaptics.com/sites/default/files/Ubuntu/pool/stable/main/all/synaptics-repository-keyring.deb"
    dest: "{{ local_home }}/Downloads/synaptics-repository-keyring.deb"

- name: Install DisplayLink APT repository keyring
  apt:
    deb: "{{ local_home }}/Downloads/synaptics-repository-keyring.deb"
  become: yes

- name: Update APT cache
  apt:
    update_cache: yes
  become: yes

- name: Install DisplayLink driver
  apt:
    name: displaylink-driver
    state: present
  become: yes

- name: Remove DisplayLink repository keyring package
  file:
    path: "{{ local_home }}/Downloads/synaptics-repository-keyring.deb"
    state: absent
