---
- name: Install dkms (required for DisplayLink)
  apt:
    name: dkms
    state: present
  become: yes

- name: Create Downloads directory
  file:
    path: "{{ local_home }}/Downloads"
    state: directory

- name: Download Synaptics APT repository keyring
  get_url:
    url: "https://www.synaptics.com/sites/default/files/Ubuntu/pool/stable/main/all/synaptics-repository-keyring.deb"
    dest: "{{ local_home }}/Downloads/synaptics-repository-keyring.deb"

- name: Install Synaptics APT repository keyring
  apt:
    deb: "{{ local_home }}/Downloads/synaptics-repository-keyring.deb"
  become: yes

- name: Update apt cache for DisplayLink repo
  apt:
    update_cache: yes
  become: yes

- name: Install DisplayLink driver via APT
  apt:
    name: displaylink-driver
    state: present
  become: yes

- name: Remove Synaptics repository keyring deb
  file:
    path: "{{ local_home }}/Downloads/synaptics-repository-keyring.deb"
    state: absent
