---
- name: install common packages from brew
  homebrew: name={{ common_packages }} state=present

- name: install brew packages
  homebrew: name={{ brew_packages }} state=present

- name: install homebrew cask packages
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - firefox
    - gimp
    - handbrake
    - paintbrush
    - vlc
    - xquartz
