---
- name: install common packages from brew
  homebrew: name={{ item }} state=present
  with_items: '{{ common_packages }}'

- name: install brew packages
  homebrew: name={{ item }} state=present
  with_items: '{{ brew_packages }}'

- name: install homebrew cask packages
  homebrew_cask: name={{ item }} state=present
  with_items:
    - atom
    - firefox
    - google-chrome
    - google-cloud-sdk
    - gimp
    - handbrake
    - iterm2
    - java
    - logitech-myharmony
    - postman
    - paintbrush
    - sonos
    - virtualbox
    - visual-studio-code
    - vlc
    - xquartz
