---
# This playbook contains common plays that will be run on all nodes.

# for 1.6 this ansible
- name: Create en_US.UTF-8 locale
  locale_gen: name=en_US.UTF-8 state=present

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install ubuntu common packages
  apt: pkg={{ common_packages }} state=present
  become: yes

- name: Install ubuntu packages
  apt: pkg={{ install_ubuntu_packages }} state=present
  become: yes

- name: Remove Ubuntu packages
  apt: pkg={{ remove_ubuntu_packages }} state=absent
  become: yes
