---
# This playbook contains common plays that will be run on all nodes.

# for 1.6 this ansible
- name: Create en_US.UTF-8 locale
  locale_gen: name=en_US.UTF-8 state=present

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Upgrade
  apt: upgrade=dist
  become: yes

- name: Install ubuntu packages
  apt: pkg={{ item }} state=present
  become: yes
  with_items:
    - alsa-base
    - alsa-utils
    - apt-transport-https
    - aptitude
    - ca-certificates
    - chrony
    - bash-completion
    - bluez
    - build-essential
    - dkms
    - git-core
    - git-flow
    - git-email
    - git-extras
    - golang-go
    - gnupg-agent
    - gstreamer1.0-alsa
    - gstreamer1.0-plugins-base-apps
    - gstreamer1.0-pulseaudio
    - gzip
    - htop
    - linux-headers-generic
    - openssh-server
    - pwgen
    - pulseaudio
    - software-properties-common
    - silversearcher-ag
    - tmux
    - terminator
    - tcpdump
    - tar
    - unzip
    - ubuntu-restricted-extras
    - vim
    - vim-gtk
    - wireless-tools
    - xorg

- name: Install common packages
  apt: pkg={{ item }} state=present
  become: yes
  with_items: '{{ common_packages }}'

- name: Remove packages 
  apt: pkg={{ item }} state=absent
  become: yes
  with_items:
    - aisleriot
    - ack
    - gbrainy
    - gnome-mines
    - gnome-sudoku
    - gnome-mahjongg
    - gnome-games-common
    - libgnome-games-support-common
    - unity-webapps-common 
