- name: Add Docker signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

- name: Add Docker signing key
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: Update cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install docker apt packages 
  apt: pkg={{ item }} state=present
  become: yes
  with_items:
  - docker-ce
  - docker-ce-cli
  - containerd.io

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
  become: yes
